# Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0

name: Canary
on:
  workflow_dispatch:

jobs:
  canary:
    name: Canary
    runs-on: ubuntu-latest
    steps:
    - name: Invoke canary in aws-sdk-rust
      run: echo "Hello World"
